// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package order

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	orderPreorderItemsFieldNames          = builder.RawFieldNames(&OrderPreorderItems{})
	orderPreorderItemsRows                = strings.Join(orderPreorderItemsFieldNames, ",")
	orderPreorderItemsRowsExpectAutoSet   = strings.Join(stringx.Remove(orderPreorderItemsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	orderPreorderItemsRowsWithPlaceHolder = strings.Join(stringx.Remove(orderPreorderItemsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheOrderPreorderItemsIdPrefix = "cache:orderPreorderItems:id:"
)

type (
	orderPreorderItemsModel interface {
		Insert(ctx context.Context, data *OrderPreorderItems) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*OrderPreorderItems, error)
		Update(ctx context.Context, data *OrderPreorderItems) error
		Delete(ctx context.Context, id int64) error
	}

	defaultOrderPreorderItemsModel struct {
		sqlc.CachedConn
		table string
	}

	OrderPreorderItems struct {
		Id         int64          `db:"id"`
		PreorderId int64          `db:"preorder_id"` // 预订单ID
		ProductId  int64          `db:"product_id"`  // 商品ID
		Quantity   int64          `db:"quantity"`    // 商品数量
		PriceCents int64          `db:"price_cents"` // 结账的快照单价(分)
		Snapshot   sql.NullString `db:"snapshot"`    // 商品的各种信息
		CreatedAt  time.Time      `db:"created_at"`
	}
)

func newOrderPreorderItemsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultOrderPreorderItemsModel {
	return &defaultOrderPreorderItemsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`order_preorder_items`",
	}
}

func (m *defaultOrderPreorderItemsModel) Delete(ctx context.Context, id int64) error {
	orderPreorderItemsIdKey := fmt.Sprintf("%s%v", cacheOrderPreorderItemsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, orderPreorderItemsIdKey)
	return err
}

func (m *defaultOrderPreorderItemsModel) FindOne(ctx context.Context, id int64) (*OrderPreorderItems, error) {
	orderPreorderItemsIdKey := fmt.Sprintf("%s%v", cacheOrderPreorderItemsIdPrefix, id)
	var resp OrderPreorderItems
	err := m.QueryRowCtx(ctx, &resp, orderPreorderItemsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", orderPreorderItemsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrderPreorderItemsModel) Insert(ctx context.Context, data *OrderPreorderItems) (sql.Result, error) {
	orderPreorderItemsIdKey := fmt.Sprintf("%s%v", cacheOrderPreorderItemsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, orderPreorderItemsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.PreorderId, data.ProductId, data.Quantity, data.PriceCents, data.Snapshot)
	}, orderPreorderItemsIdKey)
	return ret, err
}

func (m *defaultOrderPreorderItemsModel) Update(ctx context.Context, data *OrderPreorderItems) error {
	orderPreorderItemsIdKey := fmt.Sprintf("%s%v", cacheOrderPreorderItemsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, orderPreorderItemsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.PreorderId, data.ProductId, data.Quantity, data.PriceCents, data.Snapshot, data.Id)
	}, orderPreorderItemsIdKey)
	return err
}

func (m *defaultOrderPreorderItemsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheOrderPreorderItemsIdPrefix, primary)
}

func (m *defaultOrderPreorderItemsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", orderPreorderItemsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOrderPreorderItemsModel) tableName() string {
	return m.table
}
