// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package order

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	orderPreordersFieldNames          = builder.RawFieldNames(&OrderPreorders{})
	orderPreordersRows                = strings.Join(orderPreordersFieldNames, ",")
	orderPreordersRowsExpectAutoSet   = strings.Join(stringx.Remove(orderPreordersFieldNames, "`preorder_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	orderPreordersRowsWithPlaceHolder = strings.Join(stringx.Remove(orderPreordersFieldNames, "`preorder_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheOrderPreordersPreorderIdPrefix = "cache:orderPreorders:preorderId:"
)

type (
	orderPreordersModel interface {
		Insert(ctx context.Context, data *OrderPreorders) (sql.Result, error)
		FindOne(ctx context.Context, preorderId int64) (*OrderPreorders, error)
		Update(ctx context.Context, data *OrderPreorders) error
		Delete(ctx context.Context, preorderId int64) error
	}

	defaultOrderPreordersModel struct {
		sqlc.CachedConn
		table string
	}

	OrderPreorders struct {
		PreorderId     int64     `db:"preorder_id"`     // 预订单ID
		UserId         int64     `db:"user_id"`         // 用户ID
		CouponId       int64     `db:"coupon_id"`       // 优惠券ID
		OriginalAmount int64     `db:"original_amount"` // 原始金额
		FinalAmount    int64     `db:"final_amount"`    // 最终金额
		Status         string    `db:"status"`          // 状态，预下单状态，已下单，取消
		ExpireAt       time.Time `db:"expire_at"`       // 预订单过期时间
		CreatedAt      time.Time `db:"created_at"`
		UpdatedAt      time.Time `db:"updated_at"`
	}
)

func newOrderPreordersModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultOrderPreordersModel {
	return &defaultOrderPreordersModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`order_preorders`",
	}
}

func (m *defaultOrderPreordersModel) Delete(ctx context.Context, preorderId int64) error {
	orderPreordersPreorderIdKey := fmt.Sprintf("%s%v", cacheOrderPreordersPreorderIdPrefix, preorderId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `preorder_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, preorderId)
	}, orderPreordersPreorderIdKey)
	return err
}

func (m *defaultOrderPreordersModel) FindOne(ctx context.Context, preorderId int64) (*OrderPreorders, error) {
	orderPreordersPreorderIdKey := fmt.Sprintf("%s%v", cacheOrderPreordersPreorderIdPrefix, preorderId)
	var resp OrderPreorders
	err := m.QueryRowCtx(ctx, &resp, orderPreordersPreorderIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `preorder_id` = ? limit 1", orderPreordersRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, preorderId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrderPreordersModel) Insert(ctx context.Context, data *OrderPreorders) (sql.Result, error) {
	orderPreordersPreorderIdKey := fmt.Sprintf("%s%v", cacheOrderPreordersPreorderIdPrefix, data.PreorderId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, orderPreordersRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.CouponId, data.OriginalAmount, data.FinalAmount, data.Status, data.ExpireAt)
	}, orderPreordersPreorderIdKey)
	return ret, err
}

func (m *defaultOrderPreordersModel) Update(ctx context.Context, data *OrderPreorders) error {
	orderPreordersPreorderIdKey := fmt.Sprintf("%s%v", cacheOrderPreordersPreorderIdPrefix, data.PreorderId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `preorder_id` = ?", m.table, orderPreordersRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.CouponId, data.OriginalAmount, data.FinalAmount, data.Status, data.ExpireAt, data.PreorderId)
	}, orderPreordersPreorderIdKey)
	return err
}

func (m *defaultOrderPreordersModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheOrderPreordersPreorderIdPrefix, primary)
}

func (m *defaultOrderPreordersModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `preorder_id` = ? limit 1", orderPreordersRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOrderPreordersModel) tableName() string {
	return m.table
}
