// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: cart.proto

package cart

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCartItemListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartItemListReq) Reset() {
	*x = GetCartItemListReq{}
	mi := &file_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartItemListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartItemListReq) ProtoMessage() {}

func (x *GetCartItemListReq) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartItemListReq.ProtoReflect.Descriptor instead.
func (*GetCartItemListReq) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{0}
}

func (x *GetCartItemListReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetCartItemListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*CartInfoResp        `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartItemListResp) Reset() {
	*x = GetCartItemListResp{}
	mi := &file_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartItemListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartItemListResp) ProtoMessage() {}

func (x *GetCartItemListResp) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartItemListResp.ProtoReflect.Descriptor instead.
func (*GetCartItemListResp) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{1}
}

func (x *GetCartItemListResp) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetCartItemListResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *GetCartItemListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetCartItemListResp) GetData() []*CartInfoResp {
	if x != nil {
		return x.Data
	}
	return nil
}

type CartInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartInfoResp) Reset() {
	*x = CartInfoResp{}
	mi := &file_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartInfoResp) ProtoMessage() {}

func (x *CartInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartInfoResp.ProtoReflect.Descriptor instead.
func (*CartInfoResp) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{2}
}

func (x *CartInfoResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CartInfoResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CartInfoResp) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CartInfoResp) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type DelCartItemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelCartItemReq) Reset() {
	*x = DelCartItemReq{}
	mi := &file_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelCartItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelCartItemReq) ProtoMessage() {}

func (x *DelCartItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelCartItemReq.ProtoReflect.Descriptor instead.
func (*DelCartItemReq) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{3}
}

func (x *DelCartItemReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DelCartItemReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type CreateCartItemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCartItemReq) Reset() {
	*x = CreateCartItemReq{}
	mi := &file_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCartItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCartItemReq) ProtoMessage() {}

func (x *CreateCartItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCartItemReq.ProtoReflect.Descriptor instead.
func (*CreateCartItemReq) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCartItemReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateCartItemReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateCartItemReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UpdateCartItemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCartItemReq) Reset() {
	*x = UpdateCartItemReq{}
	mi := &file_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCartItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCartItemReq) ProtoMessage() {}

func (x *UpdateCartItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCartItemReq.ProtoReflect.Descriptor instead.
func (*UpdateCartItemReq) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateCartItemReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateCartItemReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateCartItemReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CartItemResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItemResp) Reset() {
	*x = CartItemResp{}
	mi := &file_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItemResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemResp) ProtoMessage() {}

func (x *CartItemResp) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemResp.ProtoReflect.Descriptor instead.
func (*CartItemResp) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{6}
}

func (x *CartItemResp) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CartItemResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

var File_cart_proto protoreflect.FileDescriptor

const file_cart_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"cart.proto\x12\x04cart\"-\n" +
	"\x12GetCartItemListReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x93\x01\n" +
	"\x13GetCartItemListResp\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12&\n" +
	"\x04data\x18\x04 \x03(\v2\x12.cart.CartInfoRespR\x04data\"r\n" +
	"\fCartInfoResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\"H\n" +
	"\x0eDelCartItemReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\"a\n" +
	"\x11CreateCartItemReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\"a\n" +
	"\x11UpdateCartItemReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\"N\n" +
	"\fCartItemResp\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg2\x8c\x02\n" +
	"\vCartService\x12F\n" +
	"\x0fGetCartItemList\x12\x18.cart.GetCartItemListReq\x1a\x19.cart.GetCartItemListResp\x12:\n" +
	"\vAddCartItem\x12\x17.cart.CreateCartItemReq\x1a\x12.cart.CartItemResp\x12=\n" +
	"\x0eUpdateCartItem\x12\x17.cart.UpdateCartItemReq\x1a\x12.cart.CartItemResp\x12:\n" +
	"\x0eDeleteCartItem\x12\x14.cart.DelCartItemReq\x1a\x12.cart.CartItemRespB\bZ\x06./cartb\x06proto3"

var (
	file_cart_proto_rawDescOnce sync.Once
	file_cart_proto_rawDescData []byte
)

func file_cart_proto_rawDescGZIP() []byte {
	file_cart_proto_rawDescOnce.Do(func() {
		file_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cart_proto_rawDesc), len(file_cart_proto_rawDesc)))
	})
	return file_cart_proto_rawDescData
}

var file_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cart_proto_goTypes = []any{
	(*GetCartItemListReq)(nil),  // 0: cart.GetCartItemListReq
	(*GetCartItemListResp)(nil), // 1: cart.GetCartItemListResp
	(*CartInfoResp)(nil),        // 2: cart.CartInfoResp
	(*DelCartItemReq)(nil),      // 3: cart.DelCartItemReq
	(*CreateCartItemReq)(nil),   // 4: cart.CreateCartItemReq
	(*UpdateCartItemReq)(nil),   // 5: cart.UpdateCartItemReq
	(*CartItemResp)(nil),        // 6: cart.CartItemResp
}
var file_cart_proto_depIdxs = []int32{
	2, // 0: cart.GetCartItemListResp.data:type_name -> cart.CartInfoResp
	0, // 1: cart.CartService.GetCartItemList:input_type -> cart.GetCartItemListReq
	4, // 2: cart.CartService.AddCartItem:input_type -> cart.CreateCartItemReq
	5, // 3: cart.CartService.UpdateCartItem:input_type -> cart.UpdateCartItemReq
	3, // 4: cart.CartService.DeleteCartItem:input_type -> cart.DelCartItemReq
	1, // 5: cart.CartService.GetCartItemList:output_type -> cart.GetCartItemListResp
	6, // 6: cart.CartService.AddCartItem:output_type -> cart.CartItemResp
	6, // 7: cart.CartService.UpdateCartItem:output_type -> cart.CartItemResp
	6, // 8: cart.CartService.DeleteCartItem:output_type -> cart.CartItemResp
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cart_proto_init() }
func file_cart_proto_init() {
	if File_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cart_proto_rawDesc), len(file_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cart_proto_goTypes,
		DependencyIndexes: file_cart_proto_depIdxs,
		MessageInfos:      file_cart_proto_msgTypes,
	}.Build()
	File_cart_proto = out.File
	file_cart_proto_goTypes = nil
	file_cart_proto_depIdxs = nil
}
