// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ChatRequest struct {
	Query string `form:"query"`
}

type ChatResponse struct {
	Status_code int32
	Status_msg  string
	Answer      string
	Items       []Recommendation
}

type Recommendation struct {
	Product_id int64
	Name       string
	Reason     string
	Price      int64
	Picture    string
	Categories []string
}
