// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: inventory.proto

package inventoryservice

import (
	"context"

	"NatsumeAI/app/services/inventory/inventory"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateInventoryReq = inventory.CreateInventoryReq
	DeleteInventoryReq = inventory.DeleteInventoryReq
	GetInventoryItem   = inventory.GetInventoryItem
	GetInventoryReq    = inventory.GetInventoryReq
	GetInventoryResp   = inventory.GetInventoryResp
	InventoryReq       = inventory.InventoryReq
	InventoryResp      = inventory.InventoryResp
	Items              = inventory.Items
	ReturnTokenReq     = inventory.ReturnTokenReq
	TryGetTokenReq     = inventory.TryGetTokenReq
	UpdateInventoryReq = inventory.UpdateInventoryReq

	InventoryService interface {
		// 获取库存
		GetInventory(ctx context.Context, in *GetInventoryReq, opts ...grpc.CallOption) (*GetInventoryResp, error)
		// 更新库存，商家调用
		UpdateInventory(ctx context.Context, in *UpdateInventoryReq, opts ...grpc.CallOption) (*InventoryResp, error)
		// 结账的时候，根据库存快速发放令牌
		TryGetToken(ctx context.Context, in *TryGetTokenReq, opts ...grpc.CallOption) (*InventoryResp, error)
		// 归还令牌
		ReturnToken(ctx context.Context, in *ReturnTokenReq, opts ...grpc.CallOption) (*InventoryResp, error)
		// 预扣
		DecreasePreInventory(ctx context.Context, in *InventoryReq, opts ...grpc.CallOption) (*InventoryResp, error)
		// 实际扣减
		DecreaseInventory(ctx context.Context, in *InventoryReq, opts ...grpc.CallOption) (*InventoryResp, error)
		// 归还预扣
		ReturnPreInventory(ctx context.Context, in *InventoryReq, opts ...grpc.CallOption) (*InventoryResp, error)
		// 归还库存
		ReturnInventory(ctx context.Context, in *InventoryReq, opts ...grpc.CallOption) (*InventoryResp, error)
		// 为商品创建库存
		CreateInventory(ctx context.Context, in *CreateInventoryReq, opts ...grpc.CallOption) (*InventoryResp, error)
		// 删除商品的时候同时调用这个
		DeleteInventory(ctx context.Context, in *DeleteInventoryReq, opts ...grpc.CallOption) (*InventoryResp, error)
	}

	defaultInventoryService struct {
		cli zrpc.Client
	}
)

func NewInventoryService(cli zrpc.Client) InventoryService {
	return &defaultInventoryService{
		cli: cli,
	}
}

// 获取库存
func (m *defaultInventoryService) GetInventory(ctx context.Context, in *GetInventoryReq, opts ...grpc.CallOption) (*GetInventoryResp, error) {
	client := inventory.NewInventoryServiceClient(m.cli.Conn())
	return client.GetInventory(ctx, in, opts...)
}

// 更新库存，商家调用
func (m *defaultInventoryService) UpdateInventory(ctx context.Context, in *UpdateInventoryReq, opts ...grpc.CallOption) (*InventoryResp, error) {
	client := inventory.NewInventoryServiceClient(m.cli.Conn())
	return client.UpdateInventory(ctx, in, opts...)
}

// 结账的时候，根据库存快速发放令牌
func (m *defaultInventoryService) TryGetToken(ctx context.Context, in *TryGetTokenReq, opts ...grpc.CallOption) (*InventoryResp, error) {
	client := inventory.NewInventoryServiceClient(m.cli.Conn())
	return client.TryGetToken(ctx, in, opts...)
}

// 归还令牌
func (m *defaultInventoryService) ReturnToken(ctx context.Context, in *ReturnTokenReq, opts ...grpc.CallOption) (*InventoryResp, error) {
	client := inventory.NewInventoryServiceClient(m.cli.Conn())
	return client.ReturnToken(ctx, in, opts...)
}

// 预扣
func (m *defaultInventoryService) DecreasePreInventory(ctx context.Context, in *InventoryReq, opts ...grpc.CallOption) (*InventoryResp, error) {
	client := inventory.NewInventoryServiceClient(m.cli.Conn())
	return client.DecreasePreInventory(ctx, in, opts...)
}

// 实际扣减
func (m *defaultInventoryService) DecreaseInventory(ctx context.Context, in *InventoryReq, opts ...grpc.CallOption) (*InventoryResp, error) {
	client := inventory.NewInventoryServiceClient(m.cli.Conn())
	return client.DecreaseInventory(ctx, in, opts...)
}

// 归还预扣
func (m *defaultInventoryService) ReturnPreInventory(ctx context.Context, in *InventoryReq, opts ...grpc.CallOption) (*InventoryResp, error) {
	client := inventory.NewInventoryServiceClient(m.cli.Conn())
	return client.ReturnPreInventory(ctx, in, opts...)
}

// 归还库存
func (m *defaultInventoryService) ReturnInventory(ctx context.Context, in *InventoryReq, opts ...grpc.CallOption) (*InventoryResp, error) {
	client := inventory.NewInventoryServiceClient(m.cli.Conn())
	return client.ReturnInventory(ctx, in, opts...)
}

// 为商品创建库存
func (m *defaultInventoryService) CreateInventory(ctx context.Context, in *CreateInventoryReq, opts ...grpc.CallOption) (*InventoryResp, error) {
	client := inventory.NewInventoryServiceClient(m.cli.Conn())
	return client.CreateInventory(ctx, in, opts...)
}

// 删除商品的时候同时调用这个
func (m *defaultInventoryService) DeleteInventory(ctx context.Context, in *DeleteInventoryReq, opts ...grpc.CallOption) (*InventoryResp, error) {
	client := inventory.NewInventoryServiceClient(m.cli.Conn())
	return client.DeleteInventory(ctx, in, opts...)
}
