// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: coupon.proto

package server

import (
	"context"

	"NatsumeAI/app/services/coupon/coupon"
	"NatsumeAI/app/services/coupon/internal/logic"
	"NatsumeAI/app/services/coupon/internal/svc"
)

type CouponServiceServer struct {
	svcCtx *svc.ServiceContext
	coupon.UnimplementedCouponServiceServer
}

func NewCouponServiceServer(svcCtx *svc.ServiceContext) *CouponServiceServer {
	return &CouponServiceServer{
		svcCtx: svcCtx,
	}
}

// 领取优惠券
func (s *CouponServiceServer) ClaimCoupon(ctx context.Context, in *coupon.ClaimCouponReq) (*coupon.ClaimCouponResp, error) {
	l := logic.NewClaimCouponLogic(ctx, s.svcCtx)
	return l.ClaimCoupon(in)
}

// 查询用户优惠券列表
func (s *CouponServiceServer) ListUserCoupons(ctx context.Context, in *coupon.ListUserCouponsReq) (*coupon.ListUserCouponsResp, error) {
	l := logic.NewListUserCouponsLogic(ctx, s.svcCtx)
	return l.ListUserCoupons(in)
}

// 校验优惠券可用性
func (s *CouponServiceServer) ValidateCoupon(ctx context.Context, in *coupon.ValidateCouponReq) (*coupon.ValidateCouponResp, error) {
	l := logic.NewValidateCouponLogic(ctx, s.svcCtx)
	return l.ValidateCoupon(in)
}

// 锁定优惠券
func (s *CouponServiceServer) LockCoupon(ctx context.Context, in *coupon.LockCouponReq) (*coupon.LockCouponResp, error) {
	l := logic.NewLockCouponLogic(ctx, s.svcCtx)
	return l.LockCoupon(in)
}

// 释放优惠券
func (s *CouponServiceServer) ReleaseCoupon(ctx context.Context, in *coupon.ReleaseCouponReq) (*coupon.ReleaseCouponResp, error) {
	l := logic.NewReleaseCouponLogic(ctx, s.svcCtx)
	return l.ReleaseCoupon(in)
}

// 核销优惠券
func (s *CouponServiceServer) RedeemCoupon(ctx context.Context, in *coupon.RedeemCouponReq) (*coupon.RedeemCouponResp, error) {
	l := logic.NewRedeemCouponLogic(ctx, s.svcCtx)
	return l.RedeemCoupon(in)
}

// 发布/批量发券
func (s *CouponServiceServer) PublishCoupon(ctx context.Context, in *coupon.PublishCouponReq) (*coupon.PublishCouponResp, error) {
	l := logic.NewPublishCouponLogic(ctx, s.svcCtx)
	return l.PublishCoupon(in)
}
