Name: product.rpc
ListenOn: 0.0.0.0:12003
Timeout: 20000

Consul:
  Host: consul:8500 # consul endpoint
  Key: 
    product.rpc
  Meta:
    Protocol: grpc
  Tag:
    - "product-rpc" 

InventoryRpc:
  Target: consul://consul:8500/inventory.rpc?wait=14s
  NonBlock: true 

MysqlConf:
  datasource: "root:Natsume@tcp(mysql:3306)/Natsume?charset=utf8mb4&parseTime=True&loc=Local"
CacheConf:
  - Host: redis:6379
    Pass: ""
    Type: node
RedisConf:
  Host: redis:6379
  Tls: false

LogConf:
  Level: "error"

ElasticConf:
  Addresses:
    - http://elasticsearch:9200
  Username: ""
  Password: ""
  IndexName: "products"
  EmbeddingDimension: 2048

Embedding:
  BaseURL: "https://ark.cn-beijing.volces.com/api/v3"
  APIKey: ""
  Model: "doubao-embedding-large-text-250515"
