// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: payment.proto

package paymentservice

import (
	"context"

	"NatsumeAI/app/services/payment/payment"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreatePaymentReq  = payment.CreatePaymentReq
	CreatePaymentResp = payment.CreatePaymentResp
	GetPaymentReq     = payment.GetPaymentReq
	GetPaymentResp    = payment.GetPaymentResp
	PaymentInfo       = payment.PaymentInfo

	PaymentService interface {
		CreatePayment(ctx context.Context, in *CreatePaymentReq, opts ...grpc.CallOption) (*CreatePaymentResp, error)
		GetPayment(ctx context.Context, in *GetPaymentReq, opts ...grpc.CallOption) (*GetPaymentResp, error)
	}

	defaultPaymentService struct {
		cli zrpc.Client
	}
)

func NewPaymentService(cli zrpc.Client) PaymentService {
	return &defaultPaymentService{
		cli: cli,
	}
}

func (m *defaultPaymentService) CreatePayment(ctx context.Context, in *CreatePaymentReq, opts ...grpc.CallOption) (*CreatePaymentResp, error) {
	client := payment.NewPaymentServiceClient(m.cli.Conn())
	return client.CreatePayment(ctx, in, opts...)
}

func (m *defaultPaymentService) GetPayment(ctx context.Context, in *GetPaymentReq, opts ...grpc.CallOption) (*GetPaymentResp, error) {
	client := payment.NewPaymentServiceClient(m.cli.Conn())
	return client.GetPayment(ctx, in, opts...)
}
