// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CancelOrderRequest struct {
	Preorder_id int64  `json:"preorder_id,optional"`
	Order_id    int64  `json:"order_id,optional"`
	Reason      string `json:"reason,optional"`
}

type CancelOrderResponse struct {
	Status_code int64  `json:"status_code"`
	Status_msg  string `json:"status_msg"`
	Status      int32  `json:"status"` // OrderStatus enum value
}

type CheckoutRequest struct {
	Coupon_id int64 `json:"coupon_id,optional"`
	Item      Item  `json:"item"`
}

type CheckoutResponse struct {
	Status_code int64  `json:"status_code"`
	Status_msg  string `json:"status_msg"`
	Preorder_id int64  `json:"preorder_id"`
	Expired_at  int64  `json:"expired_at"`
}

type ConfirmPaymentRequest struct {
	Order_id       int64  `json:"order_id"`
	Payment_method string `json:"payment_method"`
	Payment_token  string `json:"payment_token,optional"`
}

type ConfirmPaymentResponse struct {
	Status_code int64  `json:"status_code"`
	Status_msg  string `json:"status_msg"`
	Status      int32  `json:"status"` // OrderStatus enum value
}

type GetOrderRequest struct {
	Order_id int64 `form:"order_id"`
}

type GetOrderResponse struct {
	Status_code int64     `json:"status_code"`
	Status_msg  string    `json:"status_msg"`
	Order       OrderInfo `json:"order"`
}

type Item struct {
	Product_id int64 `json:"product_id"`
	Quantity   int64 `json:"quantity"`
}

type ListOrdersRequest struct {
	Status    int32 `form:"status,optional"` // OrderStatus enum value
	Page      int64 `form:"page"`
	Page_size int64 `form:"page_size"`
}

type ListOrdersResponse struct {
	Status_code int64       `json:"status_code"`
	Status_msg  string      `json:"status_msg"`
	Orders      []OrderInfo `json:"orders"`
	Total       int64       `json:"total"`
}

type OrderInfo struct {
	Order_id         int64       `json:"order_id"`
	Preorder_id      int64       `json:"preorder_id"`
	User_id          int64       `json:"user_id"`
	Status           int32       `json:"status"` // OrderStatus enum value
	Total_amount     int64       `json:"total_amount"`
	Pay_amount       int64       `json:"pay_amount"`
	Created_at       int64       `json:"created_at"`
	Paid_at          int64       `json:"paid_at"`
	Cancelled_at     int64       `json:"cancelled_at"`
	Items            []OrderItem `json:"items"`
	Payment_method   string      `json:"payment_method"`
	Address_snapshot string      `json:"address_snapshot"`
}

type OrderItem struct {
	Product_id  int64             `json:"product_id"`
	Quantity    int64             `json:"quantity"`
	Price_cents int64             `json:"price_cents"`
	Snapshot    OrderItemSnapshot `json:"snapshot"`
}

type OrderItemSnapshot struct {
	Title       string `json:"title"`
	Cover_image string `json:"cover_image"`
	Attributes  string `json:"attributes"`
}

type PlaceOrderRequest struct {
	Preorder_id int64  `json:"preorder_id"`
	Address_id  int64  `json:"address_id,optional"`
	Coupon_id   int64  `json:"coupon_id,optional"`
	Remark      string `json:"remark,optional"`
}

type PlaceOrderResponse struct {
	Status_code int64  `json:"status_code"`
	Status_msg  string `json:"status_msg"`
	Order_id    int64  `json:"order_id"`
	Status      int32  `json:"status"` // OrderStatus enum value
}
