// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	product "NatsumeAI/app/api/product/internal/handler/product"
	product_manage "NatsumeAI/app/api/product/internal/handler/product_manage"
	"NatsumeAI/app/api/product/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/products/:productId",
					Handler: product.GetProductHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/products/feed",
					Handler: product.FeedProductsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/products/search",
					Handler: product.SearchProductsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/products",
					Handler: product_manage.CreateProductHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/products/:productId",
					Handler: product_manage.UpdateProductHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/products/:productId",
					Handler: product_manage.DeleteProductHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/products/:productId/categories",
					Handler: product_manage.AddProductCategoriesHandler(serverCtx),
				},
			}...,
		),
	)
}
