// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	inventory_manage "NatsumeAI/app/api/inventory/internal/handler/inventory_manage"
	"NatsumeAI/app/api/inventory/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/inventory",
					Handler: inventory_manage.GetInventoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/inventory",
					Handler: inventory_manage.UpdateInventoryHandler(serverCtx),
				},
			}...,
		),
	)
}
