// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: cart.proto

package cartservice

import (
	"context"

	"NatsumeAI/app/services/cart/cart"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CartInfoResp        = cart.CartInfoResp
	CartItemResp        = cart.CartItemResp
	CreateCartItemReq   = cart.CreateCartItemReq
	DelCartItemReq      = cart.DelCartItemReq
	GetCartItemListReq  = cart.GetCartItemListReq
	GetCartItemListResp = cart.GetCartItemListResp
	UpdateCartItemReq   = cart.UpdateCartItemReq

	CartService interface {
		// 用户购物车信息
		GetCartItemList(ctx context.Context, in *GetCartItemListReq, opts ...grpc.CallOption) (*GetCartItemListResp, error)
		// 添加到购物车
		AddCartItem(ctx context.Context, in *CreateCartItemReq, opts ...grpc.CallOption) (*CartItemResp, error)
		// 改变商品数量
		UpdateCartItem(ctx context.Context, in *UpdateCartItemReq, opts ...grpc.CallOption) (*CartItemResp, error)
		// 删了
		DeleteCartItem(ctx context.Context, in *DelCartItemReq, opts ...grpc.CallOption) (*CartItemResp, error)
	}

	defaultCartService struct {
		cli zrpc.Client
	}
)

func NewCartService(cli zrpc.Client) CartService {
	return &defaultCartService{
		cli: cli,
	}
}

// 用户购物车信息
func (m *defaultCartService) GetCartItemList(ctx context.Context, in *GetCartItemListReq, opts ...grpc.CallOption) (*GetCartItemListResp, error) {
	client := cart.NewCartServiceClient(m.cli.Conn())
	return client.GetCartItemList(ctx, in, opts...)
}

// 添加到购物车
func (m *defaultCartService) AddCartItem(ctx context.Context, in *CreateCartItemReq, opts ...grpc.CallOption) (*CartItemResp, error) {
	client := cart.NewCartServiceClient(m.cli.Conn())
	return client.AddCartItem(ctx, in, opts...)
}

// 改变商品数量
func (m *defaultCartService) UpdateCartItem(ctx context.Context, in *UpdateCartItemReq, opts ...grpc.CallOption) (*CartItemResp, error) {
	client := cart.NewCartServiceClient(m.cli.Conn())
	return client.UpdateCartItem(ctx, in, opts...)
}

// 删了
func (m *defaultCartService) DeleteCartItem(ctx context.Context, in *DelCartItemReq, opts ...grpc.CallOption) (*CartItemResp, error) {
	client := cart.NewCartServiceClient(m.cli.Conn())
	return client.DeleteCartItem(ctx, in, opts...)
}
