// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package userservice

import (
	"context"

	"NatsumeAI/app/services/user/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Address               = user.Address
	AddressInput          = user.AddressInput
	CreateAddressRequest  = user.CreateAddressRequest
	CreateAddressResponse = user.CreateAddressResponse
	DeleteAddressRequest  = user.DeleteAddressRequest
	DeleteAddressResponse = user.DeleteAddressResponse
	ListAddressesRequest  = user.ListAddressesRequest
	ListAddressesResponse = user.ListAddressesResponse
	LoginUserRequest      = user.LoginUserRequest
	LoginUserResponse     = user.LoginUserResponse
	RegisterUserRequest   = user.RegisterUserRequest
	RegisterUserResponse  = user.RegisterUserResponse
	UpdateAddressRequest  = user.UpdateAddressRequest
	UpdateAddressResponse = user.UpdateAddressResponse
	UserProfile           = user.UserProfile

	UserService interface {
		RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
		LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
		CreateAddress(ctx context.Context, in *CreateAddressRequest, opts ...grpc.CallOption) (*CreateAddressResponse, error)
		UpdateAddress(ctx context.Context, in *UpdateAddressRequest, opts ...grpc.CallOption) (*UpdateAddressResponse, error)
		DeleteAddress(ctx context.Context, in *DeleteAddressRequest, opts ...grpc.CallOption) (*DeleteAddressResponse, error)
		ListAddresses(ctx context.Context, in *ListAddressesRequest, opts ...grpc.CallOption) (*ListAddressesResponse, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

func (m *defaultUserService) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.RegisterUser(ctx, in, opts...)
}

func (m *defaultUserService) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.LoginUser(ctx, in, opts...)
}

func (m *defaultUserService) CreateAddress(ctx context.Context, in *CreateAddressRequest, opts ...grpc.CallOption) (*CreateAddressResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.CreateAddress(ctx, in, opts...)
}

func (m *defaultUserService) UpdateAddress(ctx context.Context, in *UpdateAddressRequest, opts ...grpc.CallOption) (*UpdateAddressResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.UpdateAddress(ctx, in, opts...)
}

func (m *defaultUserService) DeleteAddress(ctx context.Context, in *DeleteAddressRequest, opts ...grpc.CallOption) (*DeleteAddressResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.DeleteAddress(ctx, in, opts...)
}

func (m *defaultUserService) ListAddresses(ctx context.Context, in *ListAddressesRequest, opts ...grpc.CallOption) (*ListAddressesResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.ListAddresses(ctx, in, opts...)
}
