// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: order.proto

package orderservice

import (
	"context"

	"NatsumeAI/app/services/order/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CancelOrderReq     = order.CancelOrderReq
	CancelOrderResp    = order.CancelOrderResp
	CheckoutReq        = order.CheckoutReq
	CheckoutResp       = order.CheckoutResp
	ConfirmPaymentReq  = order.ConfirmPaymentReq
	ConfirmPaymentResp = order.ConfirmPaymentResp
	GetOrderReq        = order.GetOrderReq
	GetOrderResp       = order.GetOrderResp
	Item               = order.Item
	ListOrdersReq      = order.ListOrdersReq
	ListOrdersResp     = order.ListOrdersResp
	OrderInfo          = order.OrderInfo
	OrderItem          = order.OrderItem
	OrderItemSnapshot  = order.OrderItemSnapshot
	PlaceOrderReq      = order.PlaceOrderReq
	PlaceOrderResp     = order.PlaceOrderResp

	OrderService interface {
		// Checkout（结账，预订单）
		Checkout(ctx context.Context, in *CheckoutReq, opts ...grpc.CallOption) (*CheckoutResp, error)
		// 提交订单（生成正式订单）
		PlaceOrder(ctx context.Context, in *PlaceOrderReq, opts ...grpc.CallOption) (*PlaceOrderResp, error)
		// 支付确认（支付成功）
		ConfirmPayment(ctx context.Context, in *ConfirmPaymentReq, opts ...grpc.CallOption) (*ConfirmPaymentResp, error)
		// 主动取消或超时取消订单
		CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderResp, error)
		// 查询单个订单
		GetOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*GetOrderResp, error)
		// 分页查询订单
		ListOrders(ctx context.Context, in *ListOrdersReq, opts ...grpc.CallOption) (*ListOrdersResp, error)
	}

	defaultOrderService struct {
		cli zrpc.Client
	}
)

func NewOrderService(cli zrpc.Client) OrderService {
	return &defaultOrderService{
		cli: cli,
	}
}

// Checkout（结账，预订单）
func (m *defaultOrderService) Checkout(ctx context.Context, in *CheckoutReq, opts ...grpc.CallOption) (*CheckoutResp, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.Checkout(ctx, in, opts...)
}

// 提交订单（生成正式订单）
func (m *defaultOrderService) PlaceOrder(ctx context.Context, in *PlaceOrderReq, opts ...grpc.CallOption) (*PlaceOrderResp, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.PlaceOrder(ctx, in, opts...)
}

// 支付确认（支付成功）
func (m *defaultOrderService) ConfirmPayment(ctx context.Context, in *ConfirmPaymentReq, opts ...grpc.CallOption) (*ConfirmPaymentResp, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.ConfirmPayment(ctx, in, opts...)
}

// 主动取消或超时取消订单
func (m *defaultOrderService) CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderResp, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.CancelOrder(ctx, in, opts...)
}

// 查询单个订单
func (m *defaultOrderService) GetOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*GetOrderResp, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.GetOrder(ctx, in, opts...)
}

// 分页查询订单
func (m *defaultOrderService) ListOrders(ctx context.Context, in *ListOrdersReq, opts ...grpc.CallOption) (*ListOrdersResp, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.ListOrders(ctx, in, opts...)
}
