// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: coupon.proto

package couponservice

import (
	"context"

	"NatsumeAI/app/services/coupon/coupon"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ClaimCouponReq      = coupon.ClaimCouponReq
	ClaimCouponResp     = coupon.ClaimCouponResp
	CouponInfo          = coupon.CouponInfo
	ListUserCouponsReq  = coupon.ListUserCouponsReq
	ListUserCouponsResp = coupon.ListUserCouponsResp
	LockCouponReq       = coupon.LockCouponReq
	LockCouponResp      = coupon.LockCouponResp
	PublishCouponReq    = coupon.PublishCouponReq
	PublishCouponResp   = coupon.PublishCouponResp
	RedeemCouponReq     = coupon.RedeemCouponReq
	RedeemCouponResp    = coupon.RedeemCouponResp
	ReleaseCouponReq    = coupon.ReleaseCouponReq
	ReleaseCouponResp   = coupon.ReleaseCouponResp
	ValidateCouponReq   = coupon.ValidateCouponReq
	ValidateCouponResp  = coupon.ValidateCouponResp

	CouponService interface {
		// 领取优惠券
		ClaimCoupon(ctx context.Context, in *ClaimCouponReq, opts ...grpc.CallOption) (*ClaimCouponResp, error)
		// 查询用户优惠券列表
		ListUserCoupons(ctx context.Context, in *ListUserCouponsReq, opts ...grpc.CallOption) (*ListUserCouponsResp, error)
		// 校验优惠券可用性
		ValidateCoupon(ctx context.Context, in *ValidateCouponReq, opts ...grpc.CallOption) (*ValidateCouponResp, error)
		// 锁定优惠券
		LockCoupon(ctx context.Context, in *LockCouponReq, opts ...grpc.CallOption) (*LockCouponResp, error)
		// 释放优惠券
		ReleaseCoupon(ctx context.Context, in *ReleaseCouponReq, opts ...grpc.CallOption) (*ReleaseCouponResp, error)
		// 核销优惠券
		RedeemCoupon(ctx context.Context, in *RedeemCouponReq, opts ...grpc.CallOption) (*RedeemCouponResp, error)
		// 发布/批量发券
		PublishCoupon(ctx context.Context, in *PublishCouponReq, opts ...grpc.CallOption) (*PublishCouponResp, error)
	}

	defaultCouponService struct {
		cli zrpc.Client
	}
)

func NewCouponService(cli zrpc.Client) CouponService {
	return &defaultCouponService{
		cli: cli,
	}
}

// 领取优惠券
func (m *defaultCouponService) ClaimCoupon(ctx context.Context, in *ClaimCouponReq, opts ...grpc.CallOption) (*ClaimCouponResp, error) {
	client := coupon.NewCouponServiceClient(m.cli.Conn())
	return client.ClaimCoupon(ctx, in, opts...)
}

// 查询用户优惠券列表
func (m *defaultCouponService) ListUserCoupons(ctx context.Context, in *ListUserCouponsReq, opts ...grpc.CallOption) (*ListUserCouponsResp, error) {
	client := coupon.NewCouponServiceClient(m.cli.Conn())
	return client.ListUserCoupons(ctx, in, opts...)
}

// 校验优惠券可用性
func (m *defaultCouponService) ValidateCoupon(ctx context.Context, in *ValidateCouponReq, opts ...grpc.CallOption) (*ValidateCouponResp, error) {
	client := coupon.NewCouponServiceClient(m.cli.Conn())
	return client.ValidateCoupon(ctx, in, opts...)
}

// 锁定优惠券
func (m *defaultCouponService) LockCoupon(ctx context.Context, in *LockCouponReq, opts ...grpc.CallOption) (*LockCouponResp, error) {
	client := coupon.NewCouponServiceClient(m.cli.Conn())
	return client.LockCoupon(ctx, in, opts...)
}

// 释放优惠券
func (m *defaultCouponService) ReleaseCoupon(ctx context.Context, in *ReleaseCouponReq, opts ...grpc.CallOption) (*ReleaseCouponResp, error) {
	client := coupon.NewCouponServiceClient(m.cli.Conn())
	return client.ReleaseCoupon(ctx, in, opts...)
}

// 核销优惠券
func (m *defaultCouponService) RedeemCoupon(ctx context.Context, in *RedeemCouponReq, opts ...grpc.CallOption) (*RedeemCouponResp, error) {
	client := coupon.NewCouponServiceClient(m.cli.Conn())
	return client.RedeemCoupon(ctx, in, opts...)
}

// 发布/批量发券
func (m *defaultCouponService) PublishCoupon(ctx context.Context, in *PublishCouponReq, opts ...grpc.CallOption) (*PublishCouponResp, error) {
	client := coupon.NewCouponServiceClient(m.cli.Conn())
	return client.PublishCoupon(ctx, in, opts...)
}
