// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	merchant "NatsumeAI/app/api/user/internal/handler/merchant"
	user "NatsumeAI/app/api/user/internal/handler/user"
	user_address "NatsumeAI/app/api/user/internal/handler/user_address"
	"NatsumeAI/app/api/user/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/users/merchant/applications",
					Handler: merchant.ApplyMerchantHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/users/merchant/applications/:applicationId/status",
					Handler: merchant.GetMerchantApplicationStatusHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/users/login",
				Handler: user.LoginUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/users/register",
				Handler: user.RegisterUserHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/users/addresses",
					Handler: user_address.CreateUserAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/users/addresses",
					Handler: user_address.ListUserAddressesHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/users/addresses/:addressId",
					Handler: user_address.UpdateUserAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/users/addresses/:addressId",
					Handler: user_address.DeleteUserAddressHandler(serverCtx),
				},
			}...,
		),
	)
}
