// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: cart.proto

package server

import (
	"context"

	"NatsumeAI/app/services/cart/cart"
	"NatsumeAI/app/services/cart/internal/logic"
	"NatsumeAI/app/services/cart/internal/svc"
)

type CartServiceServer struct {
	svcCtx *svc.ServiceContext
	cart.UnimplementedCartServiceServer
}

func NewCartServiceServer(svcCtx *svc.ServiceContext) *CartServiceServer {
	return &CartServiceServer{
		svcCtx: svcCtx,
	}
}

// 用户购物车信息
func (s *CartServiceServer) GetCartItemList(ctx context.Context, in *cart.GetCartItemListReq) (*cart.GetCartItemListResp, error) {
	l := logic.NewGetCartItemListLogic(ctx, s.svcCtx)
	return l.GetCartItemList(in)
}

// 添加到购物车
func (s *CartServiceServer) AddCartItem(ctx context.Context, in *cart.CreateCartItemReq) (*cart.CartItemResp, error) {
	l := logic.NewAddCartItemLogic(ctx, s.svcCtx)
	return l.AddCartItem(in)
}

// 改变商品数量
func (s *CartServiceServer) UpdateCartItem(ctx context.Context, in *cart.UpdateCartItemReq) (*cart.CartItemResp, error) {
	l := logic.NewUpdateCartItemLogic(ctx, s.svcCtx)
	return l.UpdateCartItem(in)
}

// 删了
func (s *CartServiceServer) DeleteCartItem(ctx context.Context, in *cart.DelCartItemReq) (*cart.CartItemResp, error) {
	l := logic.NewDeleteCartItemLogic(ctx, s.svcCtx)
	return l.DeleteCartItem(in)
}
