// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: inventory.proto

package server

import (
	"context"

	"NatsumeAI/app/services/inventory/internal/logic"
	"NatsumeAI/app/services/inventory/internal/svc"
	"NatsumeAI/app/services/inventory/inventory"
)

type InventoryServiceServer struct {
	svcCtx *svc.ServiceContext
	inventory.UnimplementedInventoryServiceServer
}

func NewInventoryServiceServer(svcCtx *svc.ServiceContext) *InventoryServiceServer {
	return &InventoryServiceServer{
		svcCtx: svcCtx,
	}
}

// 获取库存
func (s *InventoryServiceServer) GetInventory(ctx context.Context, in *inventory.GetInventoryReq) (*inventory.GetInventoryResp, error) {
	l := logic.NewGetInventoryLogic(ctx, s.svcCtx)
	return l.GetInventory(in)
}

// 更新库存，商家调用
func (s *InventoryServiceServer) UpdateInventory(ctx context.Context, in *inventory.UpdateInventoryReq) (*inventory.InventoryResp, error) {
	l := logic.NewUpdateInventoryLogic(ctx, s.svcCtx)
	return l.UpdateInventory(in)
}

// 结账的时候，根据库存快速发放令牌
func (s *InventoryServiceServer) TryGetToken(ctx context.Context, in *inventory.TryGetTokenReq) (*inventory.InventoryResp, error) {
	l := logic.NewTryGetTokenLogic(ctx, s.svcCtx)
	return l.TryGetToken(in)
}

// 预扣
func (s *InventoryServiceServer) DecreasePreInventory(ctx context.Context, in *inventory.InventoryReq) (*inventory.InventoryResp, error) {
	l := logic.NewDecreasePreInventoryLogic(ctx, s.svcCtx)
	return l.DecreasePreInventory(in)
}

// 实际扣减
func (s *InventoryServiceServer) DecreaseInventory(ctx context.Context, in *inventory.InventoryReq) (*inventory.InventoryResp, error) {
	l := logic.NewDecreaseInventoryLogic(ctx, s.svcCtx)
	return l.DecreaseInventory(in)
}

// 归还预扣
func (s *InventoryServiceServer) ReturnPreInventory(ctx context.Context, in *inventory.InventoryReq) (*inventory.InventoryResp, error) {
	l := logic.NewReturnPreInventoryLogic(ctx, s.svcCtx)
	return l.ReturnPreInventory(in)
}

// 归还库存
func (s *InventoryServiceServer) ReturnInventory(ctx context.Context, in *inventory.InventoryReq) (*inventory.InventoryResp, error) {
	l := logic.NewReturnInventoryLogic(ctx, s.svcCtx)
	return l.ReturnInventory(in)
}

// 为商品创建库存
func (s *InventoryServiceServer) CreateInventory(ctx context.Context, in *inventory.CreateInventoryReq) (*inventory.InventoryResp, error) {
	l := logic.NewCreateInventoryLogic(ctx, s.svcCtx)
	return l.CreateInventory(in)
}

// 删除商品的时候同时调用这个
func (s *InventoryServiceServer) DeleteInventory(ctx context.Context, in *inventory.DeleteInventoryReq) (*inventory.InventoryResp, error) {
	l := logic.NewDeleteInventoryLogic(ctx, s.svcCtx)
	return l.DeleteInventory(in)
}
