// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: inventory.proto

package server

import (
	"context"

	"NatsumeAI/app/services/inventory/internal/logic"
	"NatsumeAI/app/services/inventory/internal/svc"
	"NatsumeAI/app/services/inventory/inventory"
)

type InventoryServer struct {
	svcCtx *svc.ServiceContext
	inventory.UnimplementedInventoryServiceServer
}

func NewInventoryServer(svcCtx *svc.ServiceContext) *InventoryServer {
	return &InventoryServer{
		svcCtx: svcCtx,
	}
}

// 获取库存
func (s *InventoryServer) GetInventory(ctx context.Context, in *inventory.GetInventoryReq) (*inventory.GetInventoryResp, error) {
	l := logic.NewGetInventoryLogic(ctx, s.svcCtx)
	return l.GetInventory(in)
}

// 更新库存，商家调用
func (s *InventoryServer) UpdateInventory(ctx context.Context, in *inventory.UpdateInventoryReq) (*inventory.InventoryResp, error) {
	l := logic.NewUpdateInventoryLogic(ctx, s.svcCtx)
	return l.UpdateInventory(in)
}

// 预扣
func (s *InventoryServer) DecreasePreInventory(ctx context.Context, in *inventory.InventoryReq) (*inventory.InventoryResp, error) {
	l := logic.NewDecreasePreInventoryLogic(ctx, s.svcCtx)
	return l.DecreasePreInventory(in)
}

// 实际扣减
func (s *InventoryServer) DecreaseInventory(ctx context.Context, in *inventory.InventoryReq) (*inventory.InventoryResp, error) {
	l := logic.NewDecreaseInventoryLogic(ctx, s.svcCtx)
	return l.DecreaseInventory(in)
}

// 归还预扣
func (s *InventoryServer) ReturnPreInventory(ctx context.Context, in *inventory.InventoryReq) (*inventory.InventoryResp, error) {
	l := logic.NewReturnPreInventoryLogic(ctx, s.svcCtx)
	return l.ReturnPreInventory(in)
}

// 归还库存
func (s *InventoryServer) ReturnInventory(ctx context.Context, in *inventory.InventoryReq) (*inventory.InventoryResp, error) {
	l := logic.NewReturnInventoryLogic(ctx, s.svcCtx)
	return l.ReturnInventory(in)
}

// 为商品创建库存
func (s *InventoryServer) CreateInventory(ctx context.Context, in *inventory.CreateInventoryReq) (*inventory.InventoryResp, error) {
	l := logic.NewCreateInventoryLogic(ctx, s.svcCtx)
	return l.CreateInventory(in)
}
