// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package coupon

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	couponInstancesFieldNames          = builder.RawFieldNames(&CouponInstances{})
	couponInstancesRows                = strings.Join(couponInstancesFieldNames, ",")
	couponInstancesRowsExpectAutoSet   = strings.Join(stringx.Remove(couponInstancesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	couponInstancesRowsWithPlaceHolder = strings.Join(stringx.Remove(couponInstancesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCouponInstancesIdPrefix = "cache:couponInstances:id:"
)

type (
	couponInstancesModel interface {
		Insert(ctx context.Context, data *CouponInstances) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CouponInstances, error)
		Update(ctx context.Context, data *CouponInstances) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCouponInstancesModel struct {
		sqlc.CachedConn
		table string
	}

	CouponInstances struct {
		Id             int64        `db:"id"`              // 券实例ID
		UserId         int64        `db:"user_id"`         // 持券用户ID
		Status         string       `db:"status"`          // 实例状态
		LockedPreorder int64        `db:"locked_preorder"` // 锁定的预订单ID
		LockedAt       sql.NullTime `db:"locked_at"`       // 锁定时间
		UsedOrderId    int64        `db:"used_order_id"`   // 使用的订单ID
		UsedAt         sql.NullTime `db:"used_at"`         // 使用时间
		CreatedAt      time.Time    `db:"created_at"`
		UpdatedAt      time.Time    `db:"updated_at"`
	}
)

func newCouponInstancesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCouponInstancesModel {
	return &defaultCouponInstancesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`coupon_instances`",
	}
}

func (m *defaultCouponInstancesModel) Delete(ctx context.Context, id int64) error {
	couponInstancesIdKey := fmt.Sprintf("%s%v", cacheCouponInstancesIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, couponInstancesIdKey)
	return err
}

func (m *defaultCouponInstancesModel) FindOne(ctx context.Context, id int64) (*CouponInstances, error) {
	couponInstancesIdKey := fmt.Sprintf("%s%v", cacheCouponInstancesIdPrefix, id)
	var resp CouponInstances
	err := m.QueryRowCtx(ctx, &resp, couponInstancesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", couponInstancesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCouponInstancesModel) Insert(ctx context.Context, data *CouponInstances) (sql.Result, error) {
	couponInstancesIdKey := fmt.Sprintf("%s%v", cacheCouponInstancesIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, couponInstancesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.Status, data.LockedPreorder, data.LockedAt, data.UsedOrderId, data.UsedAt)
	}, couponInstancesIdKey)
	return ret, err
}

func (m *defaultCouponInstancesModel) Update(ctx context.Context, data *CouponInstances) error {
	couponInstancesIdKey := fmt.Sprintf("%s%v", cacheCouponInstancesIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, couponInstancesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.Status, data.LockedPreorder, data.LockedAt, data.UsedOrderId, data.UsedAt, data.Id)
	}, couponInstancesIdKey)
	return err
}

func (m *defaultCouponInstancesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCouponInstancesIdPrefix, primary)
}

func (m *defaultCouponInstancesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", couponInstancesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCouponInstancesModel) tableName() string {
	return m.table
}
