// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package inventory

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	inventoryAuditFieldNames          = builder.RawFieldNames(&InventoryAudit{})
	inventoryAuditRows                = strings.Join(inventoryAuditFieldNames, ",")
	inventoryAuditRowsExpectAutoSet   = strings.Join(stringx.Remove(inventoryAuditFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	inventoryAuditRowsWithPlaceHolder = strings.Join(stringx.Remove(inventoryAuditFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheInventoryAuditIdPrefix               = "cache:inventoryAudit:id:"
	cacheInventoryAuditOrderIdProductIdPrefix = "cache:inventoryAudit:orderId:productId:"
)

type (
	inventoryAuditModel interface {
		Insert(ctx context.Context, data *InventoryAudit) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*InventoryAudit, error)
		FindOneByOrderIdProductId(ctx context.Context, orderId int64, productId int64) (*InventoryAudit, error)
		Update(ctx context.Context, data *InventoryAudit) error
		Delete(ctx context.Context, id int64) error
	}

	defaultInventoryAuditModel struct {
		sqlc.CachedConn
		table string
	}

	InventoryAudit struct {
		Id        int64     `db:"id"`         // 审计id
		OrderId   int64     `db:"order_id"`   // 对应的订单id
		ProductId int64     `db:"product_id"` // 对应的商品id
		Quantity  int64     `db:"quantity"`   // 商品的数量
		Status    string    `db:"status"`     // 库存状态，和库存原子更新
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newInventoryAuditModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultInventoryAuditModel {
	return &defaultInventoryAuditModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`inventory_audit`",
	}
}

func (m *defaultInventoryAuditModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	inventoryAuditIdKey := fmt.Sprintf("%s%v", cacheInventoryAuditIdPrefix, id)
	inventoryAuditOrderIdProductIdKey := fmt.Sprintf("%s%v:%v", cacheInventoryAuditOrderIdProductIdPrefix, data.OrderId, data.ProductId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, inventoryAuditIdKey, inventoryAuditOrderIdProductIdKey)
	return err
}

func (m *defaultInventoryAuditModel) FindOne(ctx context.Context, id int64) (*InventoryAudit, error) {
	inventoryAuditIdKey := fmt.Sprintf("%s%v", cacheInventoryAuditIdPrefix, id)
	var resp InventoryAudit
	err := m.QueryRowCtx(ctx, &resp, inventoryAuditIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", inventoryAuditRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultInventoryAuditModel) FindOneByOrderIdProductId(ctx context.Context, orderId int64, productId int64) (*InventoryAudit, error) {
	inventoryAuditOrderIdProductIdKey := fmt.Sprintf("%s%v:%v", cacheInventoryAuditOrderIdProductIdPrefix, orderId, productId)
	var resp InventoryAudit
	err := m.QueryRowIndexCtx(ctx, &resp, inventoryAuditOrderIdProductIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `order_id` = ? and `product_id` = ? limit 1", inventoryAuditRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, orderId, productId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultInventoryAuditModel) Insert(ctx context.Context, data *InventoryAudit) (sql.Result, error) {
	inventoryAuditIdKey := fmt.Sprintf("%s%v", cacheInventoryAuditIdPrefix, data.Id)
	inventoryAuditOrderIdProductIdKey := fmt.Sprintf("%s%v:%v", cacheInventoryAuditOrderIdProductIdPrefix, data.OrderId, data.ProductId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, inventoryAuditRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.OrderId, data.ProductId, data.Quantity, data.Status)
	}, inventoryAuditIdKey, inventoryAuditOrderIdProductIdKey)
	return ret, err
}

func (m *defaultInventoryAuditModel) Update(ctx context.Context, newData *InventoryAudit) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	inventoryAuditIdKey := fmt.Sprintf("%s%v", cacheInventoryAuditIdPrefix, data.Id)
	inventoryAuditOrderIdProductIdKey := fmt.Sprintf("%s%v:%v", cacheInventoryAuditOrderIdProductIdPrefix, data.OrderId, data.ProductId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, inventoryAuditRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.OrderId, newData.ProductId, newData.Quantity, newData.Status, newData.Id)
	}, inventoryAuditIdKey, inventoryAuditOrderIdProductIdKey)
	return err
}

func (m *defaultInventoryAuditModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheInventoryAuditIdPrefix, primary)
}

func (m *defaultInventoryAuditModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", inventoryAuditRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultInventoryAuditModel) tableName() string {
	return m.table
}
