// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package inventory

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	inventoryFieldNames          = builder.RawFieldNames(&Inventory{})
	inventoryRows                = strings.Join(inventoryFieldNames, ",")
	inventoryRowsExpectAutoSet   = strings.Join(stringx.Remove(inventoryFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	inventoryRowsWithPlaceHolder = strings.Join(stringx.Remove(inventoryFieldNames, "`product_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheInventoryProductIdPrefix = "cache:inventory:productId:"
)

type (
	inventoryModel interface {
		Insert(ctx context.Context, data *Inventory) (sql.Result, error)
		FindOne(ctx context.Context, productId int64) (*Inventory, error)
		Update(ctx context.Context, data *Inventory) error
		Delete(ctx context.Context, productId int64) error
	}

	defaultInventoryModel struct {
		sqlc.CachedConn
		table string
	}

	Inventory struct {
		ProductId   int64     `db:"product_id"`   // 对应的商品id
		Stock       int64     `db:"stock"`        // 现有可售库存
		Sold        int64     `db:"sold"`         // 已经售出的商品数量
		ForzenStock int64     `db:"forzen_stock"` // 冻结库存
		UpdatedAt   time.Time `db:"updated_at"`
	}
)

func newInventoryModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultInventoryModel {
	return &defaultInventoryModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`inventory`",
	}
}

func (m *defaultInventoryModel) Delete(ctx context.Context, productId int64) error {
	inventoryProductIdKey := fmt.Sprintf("%s%v", cacheInventoryProductIdPrefix, productId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `product_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, productId)
	}, inventoryProductIdKey)
	return err
}

func (m *defaultInventoryModel) FindOne(ctx context.Context, productId int64) (*Inventory, error) {
	inventoryProductIdKey := fmt.Sprintf("%s%v", cacheInventoryProductIdPrefix, productId)
	var resp Inventory
	err := m.QueryRowCtx(ctx, &resp, inventoryProductIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `product_id` = ? limit 1", inventoryRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, productId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultInventoryModel) Insert(ctx context.Context, data *Inventory) (sql.Result, error) {
	inventoryProductIdKey := fmt.Sprintf("%s%v", cacheInventoryProductIdPrefix, data.ProductId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, inventoryRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ProductId, data.Stock, data.Sold, data.ForzenStock)
	}, inventoryProductIdKey)
	return ret, err
}

func (m *defaultInventoryModel) Update(ctx context.Context, data *Inventory) error {
	inventoryProductIdKey := fmt.Sprintf("%s%v", cacheInventoryProductIdPrefix, data.ProductId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `product_id` = ?", m.table, inventoryRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Stock, data.Sold, data.ForzenStock, data.ProductId)
	}, inventoryProductIdKey)
	return err
}

func (m *defaultInventoryModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheInventoryProductIdPrefix, primary)
}

func (m *defaultInventoryModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `product_id` = ? limit 1", inventoryRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultInventoryModel) tableName() string {
	return m.table
}
