// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: inventory.proto

package inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Item) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type InventoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PreorderId    int64                  `protobuf:"varint,2,opt,name=preorder_id,json=preorderId,proto3" json:"preorder_id,omitempty"`
	Item          *Item                  `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryReq) Reset() {
	*x = InventoryReq{}
	mi := &file_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryReq) ProtoMessage() {}

func (x *InventoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryReq.ProtoReflect.Descriptor instead.
func (*InventoryReq) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *InventoryReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *InventoryReq) GetPreorderId() int64 {
	if x != nil {
		return x.PreorderId
	}
	return 0
}

func (x *InventoryReq) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type InventoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryResp) Reset() {
	*x = InventoryResp{}
	mi := &file_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryResp) ProtoMessage() {}

func (x *InventoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryResp.ProtoReflect.Descriptor instead.
func (*InventoryResp) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *InventoryResp) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *InventoryResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

type GetInventoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductIds    []int64                `protobuf:"varint,1,rep,packed,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryReq) Reset() {
	*x = GetInventoryReq{}
	mi := &file_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryReq) ProtoMessage() {}

func (x *GetInventoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryReq.ProtoReflect.Descriptor instead.
func (*GetInventoryReq) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *GetInventoryReq) GetProductIds() []int64 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

type GetInventoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Inventory     int64                  `protobuf:"varint,2,opt,name=inventory,proto3" json:"inventory,omitempty"`
	SoldCount     int64                  `protobuf:"varint,3,opt,name=sold_count,json=soldCount,proto3" json:"sold_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryItem) Reset() {
	*x = GetInventoryItem{}
	mi := &file_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryItem) ProtoMessage() {}

func (x *GetInventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryItem.ProtoReflect.Descriptor instead.
func (*GetInventoryItem) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *GetInventoryItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *GetInventoryItem) GetInventory() int64 {
	if x != nil {
		return x.Inventory
	}
	return 0
}

func (x *GetInventoryItem) GetSoldCount() int64 {
	if x != nil {
		return x.SoldCount
	}
	return 0
}

type GetInventoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	Items         []*GetInventoryItem    `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryResp) Reset() {
	*x = GetInventoryResp{}
	mi := &file_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryResp) ProtoMessage() {}

func (x *GetInventoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryResp.ProtoReflect.Descriptor instead.
func (*GetInventoryResp) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *GetInventoryResp) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetInventoryResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *GetInventoryResp) GetItems() []*GetInventoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdateInventoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	MerchantId    int64                  `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInventoryReq) Reset() {
	*x = UpdateInventoryReq{}
	mi := &file_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInventoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInventoryReq) ProtoMessage() {}

func (x *UpdateInventoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInventoryReq.ProtoReflect.Descriptor instead.
func (*UpdateInventoryReq) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateInventoryReq) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *UpdateInventoryReq) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type CreateInventoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Inventory     int64                  `protobuf:"varint,2,opt,name=inventory,proto3" json:"inventory,omitempty"`
	MerchantId    int64                  `protobuf:"varint,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInventoryReq) Reset() {
	*x = CreateInventoryReq{}
	mi := &file_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInventoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInventoryReq) ProtoMessage() {}

func (x *CreateInventoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInventoryReq.ProtoReflect.Descriptor instead.
func (*CreateInventoryReq) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *CreateInventoryReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateInventoryReq) GetInventory() int64 {
	if x != nil {
		return x.Inventory
	}
	return 0
}

func (x *CreateInventoryReq) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type DeleteInventoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	MerchantId    int64                  `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInventoryReq) Reset() {
	*x = DeleteInventoryReq{}
	mi := &file_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInventoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInventoryReq) ProtoMessage() {}

func (x *DeleteInventoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInventoryReq.ProtoReflect.Descriptor instead.
func (*DeleteInventoryReq) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteInventoryReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *DeleteInventoryReq) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type TryGetTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PreorderId    int64                  `protobuf:"varint,1,opt,name=preorder_id,json=preorderId,proto3" json:"preorder_id,omitempty"`
	Item          *Item                  `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TryGetTokenReq) Reset() {
	*x = TryGetTokenReq{}
	mi := &file_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TryGetTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryGetTokenReq) ProtoMessage() {}

func (x *TryGetTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryGetTokenReq.ProtoReflect.Descriptor instead.
func (*TryGetTokenReq) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *TryGetTokenReq) GetPreorderId() int64 {
	if x != nil {
		return x.PreorderId
	}
	return 0
}

func (x *TryGetTokenReq) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type ReturnTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PreorderId    int64                  `protobuf:"varint,1,opt,name=preorder_id,json=preorderId,proto3" json:"preorder_id,omitempty"`
	Item          []*Item                `protobuf:"bytes,2,rep,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnTokenReq) Reset() {
	*x = ReturnTokenReq{}
	mi := &file_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnTokenReq) ProtoMessage() {}

func (x *ReturnTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnTokenReq.ProtoReflect.Descriptor instead.
func (*ReturnTokenReq) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *ReturnTokenReq) GetPreorderId() int64 {
	if x != nil {
		return x.PreorderId
	}
	return 0
}

func (x *ReturnTokenReq) GetItem() []*Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type DecreaseInventoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecreaseInventoryReq) Reset() {
	*x = DecreaseInventoryReq{}
	mi := &file_inventory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecreaseInventoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecreaseInventoryReq) ProtoMessage() {}

func (x *DecreaseInventoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecreaseInventoryReq.ProtoReflect.Descriptor instead.
func (*DecreaseInventoryReq) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{11}
}

func (x *DecreaseInventoryReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

var File_inventory_proto protoreflect.FileDescriptor

const file_inventory_proto_rawDesc = "" +
	"\n" +
	"\x0finventory.proto\x12\tinventory\"A\n" +
	"\x04Item\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\"o\n" +
	"\fInventoryReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x1f\n" +
	"\vpreorder_id\x18\x02 \x01(\x03R\n" +
	"preorderId\x12#\n" +
	"\x04item\x18\x03 \x01(\v2\x0f.inventory.ItemR\x04item\"O\n" +
	"\rInventoryResp\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\"2\n" +
	"\x0fGetInventoryReq\x12\x1f\n" +
	"\vproduct_ids\x18\x01 \x03(\x03R\n" +
	"productIds\"n\n" +
	"\x10GetInventoryItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1c\n" +
	"\tinventory\x18\x02 \x01(\x03R\tinventory\x12\x1d\n" +
	"\n" +
	"sold_count\x18\x03 \x01(\x03R\tsoldCount\"\x85\x01\n" +
	"\x10GetInventoryResp\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x121\n" +
	"\x05items\x18\x03 \x03(\v2\x1b.inventory.GetInventoryItemR\x05items\"Z\n" +
	"\x12UpdateInventoryReq\x12#\n" +
	"\x04item\x18\x01 \x01(\v2\x0f.inventory.ItemR\x04item\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x03R\n" +
	"merchantId\"r\n" +
	"\x12CreateInventoryReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1c\n" +
	"\tinventory\x18\x02 \x01(\x03R\tinventory\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\x03R\n" +
	"merchantId\"T\n" +
	"\x12DeleteInventoryReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x03R\n" +
	"merchantId\"V\n" +
	"\x0eTryGetTokenReq\x12\x1f\n" +
	"\vpreorder_id\x18\x01 \x01(\x03R\n" +
	"preorderId\x12#\n" +
	"\x04item\x18\x02 \x01(\v2\x0f.inventory.ItemR\x04item\"V\n" +
	"\x0eReturnTokenReq\x12\x1f\n" +
	"\vpreorder_id\x18\x01 \x01(\x03R\n" +
	"preorderId\x12#\n" +
	"\x04item\x18\x02 \x03(\v2\x0f.inventory.ItemR\x04item\"1\n" +
	"\x14DecreaseInventoryReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId2\xf1\x05\n" +
	"\x10InventoryService\x12G\n" +
	"\fGetInventory\x12\x1a.inventory.GetInventoryReq\x1a\x1b.inventory.GetInventoryResp\x12J\n" +
	"\x0fUpdateInventory\x12\x1d.inventory.UpdateInventoryReq\x1a\x18.inventory.InventoryResp\x12B\n" +
	"\vTryGetToken\x12\x19.inventory.TryGetTokenReq\x1a\x18.inventory.InventoryResp\x12B\n" +
	"\vReturnToken\x12\x19.inventory.ReturnTokenReq\x1a\x18.inventory.InventoryResp\x12I\n" +
	"\x14DecreasePreInventory\x12\x17.inventory.InventoryReq\x1a\x18.inventory.InventoryResp\x12N\n" +
	"\x11DecreaseInventory\x12\x1f.inventory.DecreaseInventoryReq\x1a\x18.inventory.InventoryResp\x12G\n" +
	"\x12ReturnPreInventory\x12\x17.inventory.InventoryReq\x1a\x18.inventory.InventoryResp\x12D\n" +
	"\x0fReturnInventory\x12\x17.inventory.InventoryReq\x1a\x18.inventory.InventoryResp\x12J\n" +
	"\x0fCreateInventory\x12\x1d.inventory.CreateInventoryReq\x1a\x18.inventory.InventoryResp\x12J\n" +
	"\x0fDeleteInventory\x12\x1d.inventory.DeleteInventoryReq\x1a\x18.inventory.InventoryRespB\rZ\v./inventoryb\x06proto3"

var (
	file_inventory_proto_rawDescOnce sync.Once
	file_inventory_proto_rawDescData []byte
)

func file_inventory_proto_rawDescGZIP() []byte {
	file_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)))
	})
	return file_inventory_proto_rawDescData
}

var file_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_inventory_proto_goTypes = []any{
	(*Item)(nil),                 // 0: inventory.Item
	(*InventoryReq)(nil),         // 1: inventory.InventoryReq
	(*InventoryResp)(nil),        // 2: inventory.InventoryResp
	(*GetInventoryReq)(nil),      // 3: inventory.GetInventoryReq
	(*GetInventoryItem)(nil),     // 4: inventory.GetInventoryItem
	(*GetInventoryResp)(nil),     // 5: inventory.GetInventoryResp
	(*UpdateInventoryReq)(nil),   // 6: inventory.UpdateInventoryReq
	(*CreateInventoryReq)(nil),   // 7: inventory.CreateInventoryReq
	(*DeleteInventoryReq)(nil),   // 8: inventory.DeleteInventoryReq
	(*TryGetTokenReq)(nil),       // 9: inventory.TryGetTokenReq
	(*ReturnTokenReq)(nil),       // 10: inventory.ReturnTokenReq
	(*DecreaseInventoryReq)(nil), // 11: inventory.DecreaseInventoryReq
}
var file_inventory_proto_depIdxs = []int32{
	0,  // 0: inventory.InventoryReq.item:type_name -> inventory.Item
	4,  // 1: inventory.GetInventoryResp.items:type_name -> inventory.GetInventoryItem
	0,  // 2: inventory.UpdateInventoryReq.item:type_name -> inventory.Item
	0,  // 3: inventory.TryGetTokenReq.item:type_name -> inventory.Item
	0,  // 4: inventory.ReturnTokenReq.item:type_name -> inventory.Item
	3,  // 5: inventory.InventoryService.GetInventory:input_type -> inventory.GetInventoryReq
	6,  // 6: inventory.InventoryService.UpdateInventory:input_type -> inventory.UpdateInventoryReq
	9,  // 7: inventory.InventoryService.TryGetToken:input_type -> inventory.TryGetTokenReq
	10, // 8: inventory.InventoryService.ReturnToken:input_type -> inventory.ReturnTokenReq
	1,  // 9: inventory.InventoryService.DecreasePreInventory:input_type -> inventory.InventoryReq
	11, // 10: inventory.InventoryService.DecreaseInventory:input_type -> inventory.DecreaseInventoryReq
	1,  // 11: inventory.InventoryService.ReturnPreInventory:input_type -> inventory.InventoryReq
	1,  // 12: inventory.InventoryService.ReturnInventory:input_type -> inventory.InventoryReq
	7,  // 13: inventory.InventoryService.CreateInventory:input_type -> inventory.CreateInventoryReq
	8,  // 14: inventory.InventoryService.DeleteInventory:input_type -> inventory.DeleteInventoryReq
	5,  // 15: inventory.InventoryService.GetInventory:output_type -> inventory.GetInventoryResp
	2,  // 16: inventory.InventoryService.UpdateInventory:output_type -> inventory.InventoryResp
	2,  // 17: inventory.InventoryService.TryGetToken:output_type -> inventory.InventoryResp
	2,  // 18: inventory.InventoryService.ReturnToken:output_type -> inventory.InventoryResp
	2,  // 19: inventory.InventoryService.DecreasePreInventory:output_type -> inventory.InventoryResp
	2,  // 20: inventory.InventoryService.DecreaseInventory:output_type -> inventory.InventoryResp
	2,  // 21: inventory.InventoryService.ReturnPreInventory:output_type -> inventory.InventoryResp
	2,  // 22: inventory.InventoryService.ReturnInventory:output_type -> inventory.InventoryResp
	2,  // 23: inventory.InventoryService.CreateInventory:output_type -> inventory.InventoryResp
	2,  // 24: inventory.InventoryService.DeleteInventory:output_type -> inventory.InventoryResp
	15, // [15:25] is the sub-list for method output_type
	5,  // [5:15] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_inventory_proto_init() }
func file_inventory_proto_init() {
	if File_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_proto_msgTypes,
	}.Build()
	File_inventory_proto = out.File
	file_inventory_proto_goTypes = nil
	file_inventory_proto_depIdxs = nil
}
