// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: order.proto

package server

import (
	"context"

	"NatsumeAI/app/services/order/internal/logic"
	"NatsumeAI/app/services/order/internal/svc"
	"NatsumeAI/app/services/order/order"
)

type OrderServiceServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServiceServer
}

func NewOrderServiceServer(svcCtx *svc.ServiceContext) *OrderServiceServer {
	return &OrderServiceServer{
		svcCtx: svcCtx,
	}
}

// Checkout（创建订单草稿，发令牌）
func (s *OrderServiceServer) Checkout(ctx context.Context, in *order.CheckoutReq) (*order.CheckoutResp, error) {
	l := logic.NewCheckoutLogic(ctx, s.svcCtx)
	return l.Checkout(in)
}

// 提交订单（冻结库存，生成正式订单）
func (s *OrderServiceServer) PlaceOrder(ctx context.Context, in *order.PlaceOrderReq) (*order.PlaceOrderResp, error) {
	l := logic.NewPlaceOrderLogic(ctx, s.svcCtx)
	return l.PlaceOrder(in)
}

// 支付确认（支付成功）
func (s *OrderServiceServer) ConfirmPayment(ctx context.Context, in *order.ConfirmPaymentReq) (*order.ConfirmPaymentResp, error) {
	l := logic.NewConfirmPaymentLogic(ctx, s.svcCtx)
	return l.ConfirmPayment(in)
}

// 主动取消或超时取消订单
func (s *OrderServiceServer) CancelOrder(ctx context.Context, in *order.CancelOrderReq) (*order.CancelOrderResp, error) {
	l := logic.NewCancelOrderLogic(ctx, s.svcCtx)
	return l.CancelOrder(in)
}

// 查询单个订单
func (s *OrderServiceServer) GetOrder(ctx context.Context, in *order.GetOrderReq) (*order.GetOrderResp, error) {
	l := logic.NewGetOrderLogic(ctx, s.svcCtx)
	return l.GetOrder(in)
}

// 分页查询订单
func (s *OrderServiceServer) ListOrders(ctx context.Context, in *order.ListOrdersReq) (*order.ListOrdersResp, error) {
	l := logic.NewListOrdersLogic(ctx, s.svcCtx)
	return l.ListOrders(in)
}
