// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	order "NatsumeAI/app/api/order/internal/handler/order"
	"NatsumeAI/app/api/order/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/order/cancel",
					Handler: order.CancelOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/order/checkout",
					Handler: order.CheckoutHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/order/detail",
					Handler: order.GetOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/order/payment/confirm",
					Handler: order.ConfirmPaymentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/order/place",
					Handler: order.PlaceOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/orders",
					Handler: order.ListOrdersHandler(serverCtx),
				},
			}...,
		),
	)
}
