// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package user

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	merchantsFieldNames          = builder.RawFieldNames(&Merchants{})
	merchantsRows                = strings.Join(merchantsFieldNames, ",")
	merchantsRowsExpectAutoSet   = strings.Join(stringx.Remove(merchantsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	merchantsRowsWithPlaceHolder = strings.Join(stringx.Remove(merchantsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMerchantsIdPrefix     = "cache:merchants:id:"
	cacheMerchantsUserIdPrefix = "cache:merchants:userId:"
)

type (
	merchantsModel interface {
		Insert(ctx context.Context, data *Merchants) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Merchants, error)
		FindOneByUserId(ctx context.Context, userId uint64) (*Merchants, error)
		Update(ctx context.Context, data *Merchants) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMerchantsModel struct {
		sqlc.CachedConn
		table string
	}

	Merchants struct {
		Id           int64          `db:"id"`            // 商家ID
		UserId       uint64         `db:"user_id"`       // 申请人用户ID（users.id）
		ShopName     string         `db:"shop_name"`     // 店铺名称
		ContactName  string         `db:"contact_name"`  // 联系人姓名
		ContactPhone string         `db:"contact_phone"` // 联系人手机号
		Address      string         `db:"address"`       // 经营地址
		Description  sql.NullString `db:"description"`   // 其他补充说明
		Status       string         `db:"status"`        // 申请状态
		RejectReason string         `db:"reject_reason"` // 驳回原因
		ReviewedAt   sql.NullTime   `db:"reviewed_at"`   // 审核时间
		CreatedAt    time.Time      `db:"created_at"`    // 创建时间
		UpdatedAt    time.Time      `db:"updated_at"`    // 最近更新时间
	}
)

func newMerchantsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMerchantsModel {
	return &defaultMerchantsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`merchants`",
	}
}

func (m *defaultMerchantsModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	merchantsIdKey := fmt.Sprintf("%s%v", cacheMerchantsIdPrefix, id)
	merchantsUserIdKey := fmt.Sprintf("%s%v", cacheMerchantsUserIdPrefix, data.UserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, merchantsIdKey, merchantsUserIdKey)
	return err
}

func (m *defaultMerchantsModel) FindOne(ctx context.Context, id int64) (*Merchants, error) {
	merchantsIdKey := fmt.Sprintf("%s%v", cacheMerchantsIdPrefix, id)
	var resp Merchants
	err := m.QueryRowCtx(ctx, &resp, merchantsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantsModel) FindOneByUserId(ctx context.Context, userId uint64) (*Merchants, error) {
	merchantsUserIdKey := fmt.Sprintf("%s%v", cacheMerchantsUserIdPrefix, userId)
	var resp Merchants
	err := m.QueryRowIndexCtx(ctx, &resp, merchantsUserIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", merchantsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantsModel) Insert(ctx context.Context, data *Merchants) (sql.Result, error) {
	merchantsIdKey := fmt.Sprintf("%s%v", cacheMerchantsIdPrefix, data.Id)
	merchantsUserIdKey := fmt.Sprintf("%s%v", cacheMerchantsUserIdPrefix, data.UserId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, merchantsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.ShopName, data.ContactName, data.ContactPhone, data.Address, data.Description, data.Status, data.RejectReason, data.ReviewedAt)
	}, merchantsIdKey, merchantsUserIdKey)
	return ret, err
}

func (m *defaultMerchantsModel) Update(ctx context.Context, newData *Merchants) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	merchantsIdKey := fmt.Sprintf("%s%v", cacheMerchantsIdPrefix, data.Id)
	merchantsUserIdKey := fmt.Sprintf("%s%v", cacheMerchantsUserIdPrefix, data.UserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, merchantsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.ShopName, newData.ContactName, newData.ContactPhone, newData.Address, newData.Description, newData.Status, newData.RejectReason, newData.ReviewedAt, newData.Id)
	}, merchantsIdKey, merchantsUserIdKey)
	return err
}

func (m *defaultMerchantsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheMerchantsIdPrefix, primary)
}

func (m *defaultMerchantsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMerchantsModel) tableName() string {
	return m.table
}
