// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package user

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userAddressesFieldNames          = builder.RawFieldNames(&UserAddresses{})
	userAddressesRows                = strings.Join(userAddressesFieldNames, ",")
	userAddressesRowsExpectAutoSet   = strings.Join(stringx.Remove(userAddressesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userAddressesRowsWithPlaceHolder = strings.Join(stringx.Remove(userAddressesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserAddressesIdPrefix = "cache:userAddresses:id:"
)

type (
	userAddressesModel interface {
		Insert(ctx context.Context, data *UserAddresses) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserAddresses, error)
		Update(ctx context.Context, data *UserAddresses) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserAddressesModel struct {
		sqlc.CachedConn
		table string
	}

	UserAddresses struct {
		Id        uint64    `db:"id"`         // 主键，搞个聚簇索引
		UserId    uint64    `db:"user_id"`    // 关联的用户id
		Detail    string    `db:"detail"`     // 懒得写太多crud，直接一个detail
		IsDefault int64     `db:"is_default"` // 是不是一个默认地址
		CreatedAt time.Time `db:"created_at"` // 创建时间
		UpdatedAt time.Time `db:"updated_at"` // 最近更新时间
	}
)

func newUserAddressesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserAddressesModel {
	return &defaultUserAddressesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_addresses`",
	}
}

func (m *defaultUserAddressesModel) Delete(ctx context.Context, id uint64) error {
	userAddressesIdKey := fmt.Sprintf("%s%v", cacheUserAddressesIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, userAddressesIdKey)
	return err
}

func (m *defaultUserAddressesModel) FindOne(ctx context.Context, id uint64) (*UserAddresses, error) {
	userAddressesIdKey := fmt.Sprintf("%s%v", cacheUserAddressesIdPrefix, id)
	var resp UserAddresses
	err := m.QueryRowCtx(ctx, &resp, userAddressesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userAddressesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAddressesModel) Insert(ctx context.Context, data *UserAddresses) (sql.Result, error) {
	userAddressesIdKey := fmt.Sprintf("%s%v", cacheUserAddressesIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, userAddressesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.Detail, data.IsDefault)
	}, userAddressesIdKey)
	return ret, err
}

func (m *defaultUserAddressesModel) Update(ctx context.Context, data *UserAddresses) error {
	userAddressesIdKey := fmt.Sprintf("%s%v", cacheUserAddressesIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userAddressesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.Detail, data.IsDefault, data.Id)
	}, userAddressesIdKey)
	return err
}

func (m *defaultUserAddressesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserAddressesIdPrefix, primary)
}

func (m *defaultUserAddressesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userAddressesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserAddressesModel) tableName() string {
	return m.table
}
