// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Address struct {
	AddressId int64  `json:"addressId,omitempty"`
	Detail    string `json:"detail"`
	IsDefault bool   `json:"isDefault,omitempty"`
	CreatedAt int64  `json:"createdAt,omitempty"`
	UpdatedAt int64  `json:"updatedAt,omitempty"`
}

type ApplyMerchantRequest struct {
	Application MerchantApplicationInput `json:"application"`
}

type ApplyMerchantResponse struct {
	ApplicationId     int64  `json:"applicationId"`
	ApplicationStatus string `json:"applicationStatus"`
}

type CreateAddressRequest struct {
	Detail    string `json:"detail"`
	IsDefault bool   `json:"isDefault"`
}

type DeleteAddressRequest struct {
	AddressId int64 `path:"addressId"`
}

type GetMerchantApplicationStatusResponse struct {
	ApplicationId     int64  `json:"applicationId"`
	ApplicationStatus string `json:"applicationStatus"`
	RejectReason      string `json:"rejectReason,omitempty"`
	ReviewedAt        int64  `json:"reviewedAt,omitempty"`
}

type ListAddressesRequest struct {
}

type ListAddressesResponse struct {
	Addresses []Address `json:"addresses"`
}

type LoginUserRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginUserResponse struct {
	AccessToken  string      `json:"-"`
	RefreshToken string      `json:"-"`
	ExpiresIn    int64       `json:"expiresIn"`
	User         UserProfile `json:"user"`
}

type MerchantApplicationInput struct {
	ShopName     string `json:"shopName"`
	ContactName  string `json:"contactName"`
	ContactPhone string `json:"contactPhone"`
	Address      string `json:"address"`
	Description  string `json:"description,omitempty"`
}

type RegisterUserRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterUserResponse struct {
	User UserProfile `json:"user"`
}

type UpdateAddressRequest struct {
	AddressId int64  `path:"addressId"`
	Detail    string `json:"detail,omitempty"`
}

type UserProfile struct {
	UserId    int64  `json:"userId"`
	Username  string `json:"username"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
}
