// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	cart "NatsumeAI/app/api/cart/internal/handler/cart"
	"NatsumeAI/app/api/cart/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/cart",
					Handler: cart.GetCartItemsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/cart",
					Handler: cart.AddCartItemHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/cart/:productId",
					Handler: cart.UpdateCartItemHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/cart/:productId",
					Handler: cart.DeleteCartItemHandler(serverCtx),
				},
			}...,
		),
	)
}
