// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	agent "NatsumeAI/app/api/agent/internal/handler/agent"
	"NatsumeAI/app/api/agent/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/agent",
					Handler: agent.ChatHandler(serverCtx),
				},
			}...,
		),
	)
}
