// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"NatsumeAI/app/services/user/internal/logic"
	"NatsumeAI/app/services/user/internal/svc"
	"NatsumeAI/app/services/user/user"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) RegisterUser(ctx context.Context, in *user.RegisterUserRequest) (*user.RegisterUserResponse, error) {
	l := logic.NewRegisterUserLogic(ctx, s.svcCtx)
	return l.RegisterUser(in)
}

func (s *UserServiceServer) LoginUser(ctx context.Context, in *user.LoginUserRequest) (*user.LoginUserResponse, error) {
	l := logic.NewLoginUserLogic(ctx, s.svcCtx)
	return l.LoginUser(in)
}

func (s *UserServiceServer) CreateAddress(ctx context.Context, in *user.CreateAddressRequest) (*user.CreateAddressResponse, error) {
	l := logic.NewCreateAddressLogic(ctx, s.svcCtx)
	return l.CreateAddress(in)
}

func (s *UserServiceServer) UpdateAddress(ctx context.Context, in *user.UpdateAddressRequest) (*user.UpdateAddressResponse, error) {
	l := logic.NewUpdateAddressLogic(ctx, s.svcCtx)
	return l.UpdateAddress(in)
}

func (s *UserServiceServer) DeleteAddress(ctx context.Context, in *user.DeleteAddressRequest) (*user.DeleteAddressResponse, error) {
	l := logic.NewDeleteAddressLogic(ctx, s.svcCtx)
	return l.DeleteAddress(in)
}

func (s *UserServiceServer) ListAddresses(ctx context.Context, in *user.ListAddressesRequest) (*user.ListAddressesResponse, error) {
	l := logic.NewListAddressesLogic(ctx, s.svcCtx)
	return l.ListAddresses(in)
}
